### ISSUE TITLE
项目编译有问题

### ISSUE THREAD

**Issue by LuciferJun1227** [buqiyuan/vue3-antd-admin#1]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-antd@0.1.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue3-antd@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by buqiyuan** [comment]
噢，这个不影响的吧，之前是因为可能要用electron做成桌面版的，所以才有这个，现在去掉了

**Comment by LuciferJun1227** [comment]
大哥,我就是想用electron,能不能加进去啊,拜托啦

**Comment by buqiyuan** [comment]
> 大哥,我就是想用electron,能不能加进去啊,拜托啦

![image](https://user-images.githubusercontent.com/39730999/95959619-4ba39780-0e35-11eb-8a11-29d733b84427.png)
你把这几个依赖放到package.json里面就可以了

**Comment by LuciferJun1227** [comment]
@buqiyuan 
![image](https://user-images.githubusercontent.com/29009277/95967728-27e54f00-0e3f-11eb-982a-4446ca637ab0.png)
加进入了还是有问题

**Comment by buqiyuan** [comment]
> @buqiyuan
> ![image](https://user-images.githubusercontent.com/29009277/95967728-27e54f00-0e3f-11eb-982a-4446ca637ab0.png)
> 加进入了还是有问题

![image](https://user-images.githubusercontent.com/39730999/95968869-924abf00-0e40-11eb-8b67-e914634557c3.png)
刚试了没问题，你是不是依赖没下载完整，electron安装依赖的时候你可能需要科学上网的

**Comment by LuciferJun1227** [comment]
@buqiyuan 应该是我环境有问题，我换了台电脑试就可以了

**Comment by LuciferJun1227** [comment]
@buqiyuan 现在vue3好像比较推荐vite，有没有可能创建一个使用vite的版本

**Comment by buqiyuan** [comment]
> @buqiyuan 现在vue3好像比较推荐vite，有没有可能创建一个使用vite的版本

换vite很简单呐，基本配置和vue.config.js差不多，如果你有需要的话，我过段时间会把当前这个模板项目重构一次，目前我在公司做的多的都是针对内网管理的项目。这个项目只是我做过的项目的其中一个样本，有时间我会把它重构得通用

**Comment by buqiyuan** [comment]
> @buqiyuan 现在vue3好像比较推荐vite，有没有可能创建一个使用vite的版本

之所以没有上vite，因为考虑到甲方可能会要求兼容IE的情况

**Comment by buqiyuan** [comment]
> @buqiyuan 刚开始摸索前端，好多还在学习中，等有空麻烦大佬重构一下吧，可以新开一个分支的，期待啊

嗯，过段时间我会提炼成一个通用的版本（也为了自己日后工作中方便速建），有很多地方为了赶时间没封装好呢
