### ISSUE TITLE
启动项目报错这个改怎么解Error: Cannot find module 'unplugin-vue-define-options/webpack'

### ISSUE THREAD

**Issue by bone-soup** [buqiyuan/vue3-antd-admin#101]
Error: Cannot find module 'unplugin-vue-define-options/webpack'

**Comment by yanbowe** [comment]
> Error: Cannot find module 'unplugin-vue-define-options/webpack'

unplugin-vue-define-options插件是否安装了？

**Comment by bone-soup** [comment]
> > Error: Cannot find module 'unplugin-vue-define-options/webpack'
> 
> unplugin-vue-define-options插件是否安装了？

安了，把路径改成“unplugin-vue-define-options/dist/webpack"就可以了
