### ISSUE TITLE
safari浏览器兼容性，build后报错defineOptions undefind

### ISSUE THREAD

**Issue by zjluse** [buqiyuan/vue3-antd-admin#108]
1.safari浏览器兼容性
fullUrl.replace(/(?<!:)\/{2,}/g, '/'), safari浏览器不再兼容该类型的正则了
2.defineOptions undefind
开发环境一切正常，build打包部署后，报defineOptions undefind， 卸载全部node_modules后再install后build又正常，重新打开编辑器后又不行了

**Comment by buqiyuan** [comment]
safari 下一代IE！
