### ISSUE TITLE
效果感觉不错，但是代码细嗯。。

### ISSUE THREAD

**Issue by luocong2016** [buqiyuan/vue3-antd-admin#12]
vue3 特性没发挥
1. setup 函数渲染组件、空标签
```
setup() {
   return () => <></>
}
```
2. use bus吗 可以看下 vant的实现
```
provide-inject
```
3. typescript 没有充分发挥，偷懒 any
4. 其中很多代码 jsx 开发效率更高，参考 @vue/babel-plugin-jsx
...

不多写了，加油

**Comment by buqiyuan** [comment]
感谢指出不足之处和建议，😅确实很多地方偷懒了，有时间再去繁从简并严格书写了
