### ISSUE TITLE
FormSchema 中如何正确使用 Upload组件?

### ISSUE THREAD

**Issue by suchafool** [buqiyuan/vue3-antd-admin#120]
在模式窗口中使用Upload组件，界面上始终无法显示，正确的使用方式是怎样的？还请大佬不吝赐教。

FormSchema中的代码如下：

    {
        field: 'cover',
        component: 'Upload',
        label: '封面',
        componentProps: {
          action: '/',
          listType: 'picture-card',
        },
      }

**Comment by buqiyuan** [comment]
[实例代码](https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/views/demos/form/basic-form/form-schema.tsx#L497)
[在线demo](https://vue3-antd-admin.vercel.app/#/demos/form/basic)

**Comment by suchafool** [comment]
明白了，感谢大佬~
