### ISSUE TITLE
你这个项目有内存泄漏问题

### ISSUE THREAD

**Issue by zhuxni** [buqiyuan/vue3-antd-admin#126]
## 整个项目有内存泄漏问题
随便点几个页面就能发现这个问题。

![内存泄漏](https://user-images.githubusercontent.com/48204280/210744887-312d8457-3d09-4988-9411-1adfae1d61c8.png)

**Comment by buqiyuan** [comment]
因为我大部分路由页面都用了 `keep-alive`，然后每新开一个页面都会被缓存起来，所以内存增长很正常

**Comment by zoushanjun** [comment]
是的，经常内存溢出退出，请问有什么解决方案吗？网上找了一些资料都没有解决这个问题

**Comment by shandongtlb** [comment]
> 

宝塔面板，定期清理内存就行了

**Comment by FQIP** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
