### ISSUE TITLE
大神，tabs切换 如何保存数据状态

### ISSUE THREAD

**Issue by xlanghejianfeng** [buqiyuan/vue3-antd-admin#13]
有2个困难问题需要请教下
1.tabs切换 保留数据信息 我想了keeppalive 但是无法很好的解决
2.tree 最末一级 有办法平铺显示么
3.动态表单 能自定义一行多列扩展么

**Comment by buqiyuan** [comment]
tabs保存状态我刚加上了，动态表单多列我待会加上。然后你说的tree最末一级平铺显示具体指的是？

**Comment by xlanghejianfeng** [comment]
![image](https://user-images.githubusercontent.com/25193924/104303284-e0856200-5504-11eb-917a-710c1993ce7a.png)
类似这样

**Comment by xlanghejianfeng** [comment]
tabs 是希望 各标签里的内容 切换保留

**Comment by buqiyuan** [comment]
你说的tree那个，改css样式最快吧？用的是a-tree组件吗

**Comment by xlanghejianfeng** [comment]
a-tree 是的

**Comment by xlanghejianfeng** [comment]
如果是希望 tabs 切换 表单内容保留 用什么机制呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2021年1月12日 19:00
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神，tabs切换 如何保存数据状态 (#13)






你说的tree那个，改css样式最快吧？用的是a-tree组件吗

**Comment by buqiyuan** [comment]
希望保存主页面上的表单还是弹窗表单？

**Comment by xlanghejianfeng** [comment]
主页表单 新的一个tab 不是modal 比如新增一半 去编辑 编辑一部分回去新增



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2021年1月13日 00:11
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神，tabs切换 如何保存数据状态 (#13)






希望保存主页面上的表单还是弹窗表单？

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/104399270-4ae0e580-558b-11eb-9d96-c3f03641f7ab.png)
route mete属性加上keepAlive就可以了

**Comment by xlanghejianfeng** [comment]
多谢了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2021年1月13日 12:02
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神，tabs切换 如何保存数据状态 (#13)






Closed #13.

**Comment by xlanghejianfeng** [comment]
你好 我点击tab切换 组件空白了就

<template>
    <router-view v-slot="{ Component, route }">
        <transition name="zoom-fade" mode="out-in" appear>
            <keep-alive v-if="route.meta.keepAlive" :include="keepAliveComponents" :max="10">
                <component :is="Component" />
            </keep-alive>
            <component :is="Component" v-else />
        </transition>
    </router-view>
</template>

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/104423032-8219bb80-55b8-11eb-83e0-259731a91c40.png)
线上的我试着没问题诶，要不你给他最外层加一层div

**Comment by xlanghejianfeng** [comment]
transition加上 include加上 就没缓存效果

**Comment by buqiyuan** [comment]
不会吧？keep-alive组件加上include不是选择要缓存的组件吗？

**Comment by xlanghejianfeng** [comment]
方便加个微信么 请教帮看下 纠结了半天 也尝试了版本更新



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2021年1月13日 21:54
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神，tabs切换 如何保存数据状态 (#13)






不会吧？keep-alive组件加上include不是选择要缓存的组件吗？

**Comment by buqiyuan** [comment]
可以，bqy_fe
