### ISSUE TITLE
vite版登陆时http proxy error

### ISSUE THREAD

**Issue by smallis-2018** [buqiyuan/vue3-antd-admin#14]
[vite] http proxy error:
Error: connect ECONNREFUSED 109.166.36.55:63922
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Comment by buqiyuan** [comment]
将vite.config.ts里proxy target 替换成 http://29135jo738.zicp.vip

**Comment by buqiyuan** [comment]
我不常更新vite版的内容，建议使用vue-cli，vite还不够稳定
