### ISSUE TITLE
vuex

### ISSUE THREAD

**Issue by qdwds** [buqiyuan/vue3-antd-admin#17]
看了几次，都不太明白vuex,如何不使用命名空间直接调用的，下图这样还是在modules里面的啊。怎么做到的？
![image](https://user-images.githubusercontent.com/52602678/110065055-4ecdfe80-7da9-11eb-9e63-d155e6c1aa96.png)
![image](https://user-images.githubusercontent.com/52602678/110065079-5ab9c080-7da9-11eb-8ab7-0f56195c5441.png)

**Comment by buqiyuan** [comment]
默认情况下（不加namespace），模块内部的 action、mutation 和 getter 是注册在全局命名空间的，你打印一下store就明白了
