### ISSUE TITLE
store 里面这段代码 不是很看得懂 , 能否求请求解析一下

### ISSUE THREAD

**Issue by Little-Z-Classmates** [buqiyuan/vue3-antd-admin#18]
export type UserStore<S = State> = Omit<VuexStore<S>, 'getters' | 'commit' | 'dispatch'>
    & {
    commit<K extends keyof Mutations, P extends Parameters<Mutations[K]>[1]>(
        key: K,
        payload: P,
        options?: CommitOptions
    ): ReturnType<Mutations[K]>;
} & {
    dispatch<K extends keyof Actions>(
        key: K,
        payload?: Parameters<Actions[K]>[1],
        options?: DispatchOptions
    ): ReturnType<Actions[K]>;
} & {
    getters: {
        [K in keyof Getters]: ReturnType<Getters[K]>
    };
};

**Comment by webTianyong** [comment]
自定义 getter commit dispatch
