### ISSUE TITLE
问一下 我修改了BaseUrl为什么还是从我本地请求的呢

### ISSUE THREAD

**Issue by penghao-06** [buqiyuan/vue3-antd-admin#20]
问一下 我修改了BaseUrl为什么还是从我本地请求的呢

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/111950614-7ea53200-8b1d-11eb-8245-018158f34be9.png)
https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/utils/http/axios/index.ts
修改这里的apiUrl看下。
