### ISSUE TITLE
TypeError: Cannot read property 'upgrade' of undefined

### ISSUE THREAD

**Issue by henrycjchen** [buqiyuan/vue3-antd-admin#22]
由于获取不到 process.env.VUE_APP_API_URL1，导致 devServer 的 proxy 配置失败
解决方案：更换 target，或直接把 proxy 注释掉
```js
  devServer: {
    proxy: {
      "/api": {
        // target: process.env.VUE_APP_API_URL1,
        target: 'http://localhost:8888',
        changeOrigin: true,
        pathRewrite: {
          "^/api": ""
        }
      }
    }
  }
```

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/115217955-9ed60a00-a138-11eb-9651-10ba467d2d20.png)
你看下这两个文件里有没有定义这个变量，没有的话，自己定义一个，然后再在vue.config.js里面使用
