### ISSUE TITLE
提示Uncaught (in promise) TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by tonynii** [buqiyuan/vue3-antd-admin#23]
克隆项目到本地后，yarn serve，后打开http://localhost:8080/#/system/dict。
添加字典，开发工具console出现如下提示：
![image](https://user-images.githubusercontent.com/11513669/116179547-24197a00-a74a-11eb-9544-e90c57039177.png)

**Comment by buqiyuan** [comment]
刚试了下，没有复现这个问题，这感觉像是浏览器插件的问题，你无痕模式打开看看
