### ISSUE TITLE
yarn build error occurred

### ISSUE THREAD

**Issue by WuChenDi** [buqiyuan/vue3-antd-admin#25]
PS C:\Users\Admin\Desktop\vue3-antd-admin> yarn build
yarn run v1.22.5
$ vue-cli-service build

|  Building for production...

 ERROR  Failed to compile with 4 errors                                                                                                                                                                                                 下午4:44:38
 error  in ./node_modules/ant-design-vue/es/config-provider/style/index.less

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in C:\Users\Admin\Desktop\vue3-antd-admin\node_modules\ant-design-vue\es\style\color\bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/es/config-provider/style/index.js 1:0-22
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=ts
 @ ./src/App.vue?vue&type=script&lang=ts
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in ./node_modules/ant-design-vue/es/alert/style/index.less

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in C:\Users\Admin\Desktop\vue3-antd-admin\node_modules\ant-design-vue\es\style\color\bezierEasing.less (line 110, column 0)
    at runMicrotasks (<anonymous>)

 @ ./node_modules/ant-design-vue/es/alert/style/index.js 2:0-22
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/shared/demos/button.vue?vue&type=script&lang=ts
 @ ./src/views/shared/demos/button.vue?vue&type=script&lang=ts
 @ ./src/views/shared/demos/button.vue
 @ ./src/router/modules/demos.ts
 @ ./src/router/common.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in ./src/components/button/button.vue?vue&type=style&index=0&id=4e80b8e7&lang=less&scoped=true

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in C:\Users\Admin\Desktop\vue3-antd-admin\node_modules\ant-design-vue\lib\style\color\bezierEasing.less (line 110, column 0)

 @ ./src/components/button/button.vue?vue&type=style&index=0&id=4e80b8e7&lang=less&scoped=true 1:0-544 1:0-544
 @ ./src/components/button/button.vue
 @ ./src/components/button/index.ts
 @ ./src/plugins/antd.ts
 @ ./src/plugins/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 error  in ./src/layout/header/index.vue?vue&type=style&index=0&id=ac2fbb44&lang=scss&scoped=true

SassError: Undefined variable.
  ╷
9 │   height: $header-height;
  │           ^^^^^^^^^^^^^^
  ╵
  src\layout\header\index.vue 9:11  root stylesheet

 @ ./src/layout/header/index.vue?vue&type=style&index=0&id=ac2fbb44&lang=scss&scoped=true 1:0-539 1:0-539
 @ ./src/layout/header/index.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/layout/index.vue?vue&type=script&lang=ts
 @ ./src/layout/index.vue?vue&type=script&lang=ts
 @ ./src/layout/index.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by buqiyuan** [comment]
看着像是vue.config.js里面less和sass没配置好

**Comment by WuChenDi** [comment]
> 看着像是vue.config.js里面less和sass没配置好

git clone 运行也是如此
