### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#29]
你好，请教个问题 ，我修改了VUE_APP_API_URL和devServer访问我的后台，报错，访问不到

**Comment by buqiyuan** [comment]
报的什么错？ 404吗？可以在DevServe proxy那里开启logLevel看下代理是否正确

**Comment by stevenliu87** [comment]
对 就是404,后台服务也启动了

**Comment by stevenliu87** [comment]
你说的是 logLevel: 'debug',这个吗，在哪看代理是否正确

**Comment by buqiyuan** [comment]
在你启动项目的 cmd 中可以看到实际的代理log

**Comment by stevenliu87** [comment]
cmd中没有报错
Issues checking in progress...
No issues found.

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/126094831-d8d27f40-0a87-44f8-95bc-5388adc05b44.png)

**Comment by stevenliu87** [comment]
写了 logLevel: 'debug', 怎么没打日志呢

**Comment by stevenliu87** [comment]
请说下哪个请求的地址

**Comment by stevenliu87** [comment]
config.url = isDev ? `/psam$ 
/psam': {
          target: process.env.VUE_APP_Device,
          // target: 'http://localhost:8888',
          changeOrigin: true,
          logLevel: 'debug',
          pathRewrite: {
            '^/psam': ''
          }
adminDictConfig = '/ysdjhbbxxgl-a
这些都修改了呀

**Comment by stevenliu87** [comment]
Cannot GET /psam/ysdjhbbxxgl-a

**Comment by buqiyuan** [comment]
看着貌似没问题，修改配置后，重启项目也都不生效是吧？不应该啊！我的都正常运行啊，不知道你还有哪里配置有误，还是你后端服务端口可能和前端服务端口 是否存在多个进程监听同一端口的问题

**Comment by stevenliu87** [comment]
访问你的api就行 改成我的就不行

**Comment by buqiyuan** [comment]
😂那你通过/api能请求到你们后端吗？

**Comment by stevenliu87** [comment]
请问，  "/api/admin/access?pageNumber=1&pageSize=10&_t=1626677225474"是怎么映射到 "/admin/access?p的

**Comment by buqiyuan** [comment]
pathRewrite那里在映射到目标地址前，把/api替换掉了

**Comment by stevenliu87** [comment]
谢谢你，好了

**Comment by buqiyuan** [comment]
好的
