### ISSUE TITLE
大神 有没有封装个搜索筛选table的组件

### ISSUE THREAD

**Issue by xlanghejianfeng** [buqiyuan/vue3-antd-admin#3]

**Comment by buqiyuan** [comment]
这个目前没有封装，过两天我封装一下，顺便把nestjs 写的配套后台也一并开源出来

**Comment by xlanghejianfeng** [comment]
抱拳，多谢分享 正在使用3.0 有很多思想可以参考借鉴

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/100623651-67b7b580-335d-11eb-8d25-d4e7642cbeac.png)
刚刚看了下，官方好像就提供了搜索筛选的slot选项，我表格的封装是继承式封装，只是扩展了官方组件，你还是可以像官方原组件一样正常使用的

**Comment by buqiyuan** [comment]
噢，不过里面的搜索逻辑是可以封装出来，将某列的搜索筛选封装为可配置的 是否启用 的配置项

**Comment by xlanghejianfeng** [comment]
可以的，封装成字段以及控件筛选 比如日历 下拉框 输入框 区间等等 然后拼接成自定义条件参数传给接口 获取data 更新table数据



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2020年11月30日 22:53
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神 有没有封装个搜索筛选table的组件 (#3)






噢，不过里面的搜索逻辑是可以封装出来，将某列的搜索筛选封装为可配置的 是否启用 的配置项

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/100630170-2deaad00-3365-11eb-90d5-22b562c0fd53.png)
嗯，我本意是想封装成易于扩展和控制的轻量通用组件，使用者可以在外部任意扩展或调用表格内部的属性方法，像日历、下拉框那些可以封装成配置项，但这样的话，这个组件就显得有些重了

**Comment by xlanghejianfeng** [comment]
对的 配置项 这样会更灵活高效&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2020年11月30日 23:52
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神 有没有封装个搜索筛选table的组件 (#3)







嗯，我本意是想封装成易于扩展和控制的轻量通用组件，使用者可以在外部任意扩展或调用表格内部的属性方法，像日历、下拉框那些可以封装成配置项，但这样的话，这个组件就显得有些重了

**Comment by xlanghejianfeng** [comment]
好 我明天再研究下文档



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2020年11月30日 22:48
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神 有没有封装个搜索筛选table的组件 (#3)







刚刚看了下，官方好像就提供了搜索筛选的slot选项，我表格的封装是继承式封装，只是扩展了官方组件，你还是可以像官方原组件一样正常使用的
