### ISSUE TITLE
左侧导航菜单的icon图标在不同的theme主题的显示问题

### ISSUE THREAD

**Issue by Guolinlinaaa** [buqiyuan/vue3-antd-admin#30]
你项目中的是使用的dark主题  然后是黑色的主题 显示图标时正常，但是当我换成light主题时 就会不显示图标了。

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/126415733-1dcff084-7617-4036-85fb-71fa4c3c2ad3.png)
把这个 style="color: aliceblue" 这个去掉就可以了，之前不知怎么的写死了一个颜色

**Comment by Guolinlinaaa** [comment]
谢谢
