### ISSUE TITLE
请教，在table中实现点击 编辑，跳转路由，打开新页面或者打开a-drawer，怎么实现

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#37]
请教，在table中实现点击 编辑，跳转路由，打开新页面或者打开a-drawer，怎么实现，请回复，急用

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/131440415-72c9d838-bab8-4a1f-8307-6f49ccef931e.png)

你可以把columns定义成一个函数来返回，然后你就可以传state等了

**Comment by stevenliu87** [comment]
给个实例代码吧 还有路由跳转的

**Comment by stevenliu87** [comment]
你很长时间没更新代码了

**Comment by stevenliu87** [comment]
回复下吧

**Comment by buqiyuan** [comment]
> 给个实例代码吧 还有路由跳转的

![image](https://user-images.githubusercontent.com/39730999/131452904-27a2a425-1f4a-46f6-92bf-c8b69e98d18e.png)

你定义一个类似getColumns函数 把外部的东西传进去就行了 然后在getColumns内部使用外部对象就行了呀
