### ISSUE TITLE
动态表格怎么让它进入页面不自动触发查询

### ISSUE THREAD

**Issue by hao117** [buqiyuan/vue3-antd-admin#41]
动态表格怎么让它进入页面不自动触发查询

**Comment by yanbowe** [comment]
1.找到dymamic-table组件
2.找到refreshTableData方法
3.自己加个参数控制，通过props传进来

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/132078266-54c468ff-8c3d-47ad-98e6-468ee46076d9.png)
![image](https://user-images.githubusercontent.com/43030980/132078274-8cd5f1e9-9cc6-426d-b230-64ec77204735.png)

**Comment by hao117** [comment]
谢谢
