### ISSUE TITLE
请教个问题，想引用jquery-1.11.0.js文件编译时报错

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#45]
编译时，居然会检查jquery-1.11.0.js文件
TS2339: Property 'isFunction' does not exist on type 'typeof jQuery'.
着急用 请回复

**Comment by stevenliu87** [comment]
import BupAuthLoginNew from 'public/BupAuthLoginNew.js' 这样报错 ，着急用 请回复

**Comment by buqiyuan** [comment]
请不要开那么多和项目无关的issue，你这些奇奇怪怪的问题搜索引擎应该能得到解决，大多情况下可能是你代码语法或错误的使用方式问题

**Comment by stevenliu87** [comment]
抱歉，因为想在项目中应用你的代码，现在问题解决了
