### ISSUE TITLE
表格功能增强

### ISSUE THREAD

**Issue by yanbowe** [buqiyuan/vue3-antd-admin#48]
表格功能可否增强，例如自定义列以及修改列的顺序。像ant-design-pro表格功能一样
![image](https://user-images.githubusercontent.com/43030980/133355781-8219b335-2693-4448-843e-cf50d81998ae.png)

**Comment by stevenliu87** [comment]
同问，很需要这个功能

**Comment by buqiyuan** [comment]
嗯 这个没问题 目前封装功能确实太少了 都还是只个demo级别的

**Comment by yanbowe** [comment]
naive-ui-admin 有类似的功能，楼主时间匆忙的话，可以参考移植一下
[naive-ui-admin](https://naive-ui-admin.vercel.app/#/list/basic-list)

**Comment by buqiyuan** [comment]
> naive-ui-admin 有类似的功能，楼主时间匆忙的话，可以参考移植一下
> [naive-ui-admin](https://naive-ui-admin.vercel.app/#/list/basic-list)

好的

**Comment by yanbowe** [comment]
vue-vben-admin也有类似的功能
[vue-vben-admin](https://github.com/anncwb/vue-vben-admin)

**Comment by yanbowe** [comment]
> > naive-ui-admin 有类似的功能，楼主时间忙的话，可以参考一下
> > [naive-ui-admin](https://naive-ui-admin.vercel.app/#/list/basic-list)
> 
> 好

表格可否增加自适应宽高
![image](https://user-images.githubusercontent.com/43030980/134476349-b551ad01-8a91-4df7-9068-c8659cdcee60.png)

**Comment by buqiyuan** [comment]
可以的 在重构了 前后端都在重新设计

**Comment by yanbowe** [comment]
> 可以的 在重构了 前后端都在重新设计

好的，自定义列以及修改列的顺序我已实现，如果需要我可以提供下
![image](https://user-images.githubusercontent.com/43030980/134478411-9ba2aecf-2940-4069-aa86-3a56051bae0a.png)

**Comment by buqiyuan** [comment]
:thumbsup: 强！后面吧！现在我相当于重写了整个项目 变动比较大 到时候commit记录可能也会清零

**Comment by yanbowe** [comment]
期待，每天都来看一遍commit，是全部都采用script setup 写法了吗？

**Comment by buqiyuan** [comment]
是的 全部采用script setup 毕竟vscode + volar的setup语法支持已经非常perfect了

**Comment by yanbowe** [comment]
好的
