### ISSUE TITLE
页面不显示内容，请回复

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#49]
现在第一次点击菜单，页面显示正常，再点击一个菜单，页面不显示内容

**Comment by buqiyuan** [comment]
控制台有什么报错信息吗？线上的demo并未发现此问题

**Comment by stevenliu87** [comment]
[HPM] GET /api/admin/menus ~> http://29135jo738.zicp.vip/api/v1
到这就不跳转了

**Comment by stevenliu87** [comment]
刷新页面就显示正常了

**Comment by buqiyuan** [comment]
> [HPM] GET /api/admin/menus ~> http://29135jo738.zicp.vip/api/v1
> 到这就不跳转了

这个是api请求代理的log来的。你还是加我QQ：1743369777吧！
