### ISSUE TITLE
请教个问题，dynamic-table能实现 编辑行功能吗

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#50]
感觉不行，怎么指定列和key,
例如：   <template v-for="col in ['name', 'age', 'address']" #[col]="{ text, record }" :key="col">
      <div>
        <a-input
          v-if="editableData[record.key]"
          v-model:value="editableData[record.key][col]"
          style="margin: -5px 0"
        />
        
      </div>
    </template>
这样写，请回复

**Comment by buqiyuan** [comment]
column有加slots: { customRender: '' }了吗

**Comment by stevenliu87** [comment]
这个功能太实用了，有时间你扩展下吧

**Comment by stevenliu87** [comment]
加slots: { customRender: 'xxx' }了，没有用

**Comment by buqiyuan** [comment]
> 这个功能太实用了，有时间你扩展下吧

嗯 在重构了 前后端都在重新设计
