### ISSUE TITLE
请教个问题，dynamic-table中如何添加序号

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#51]
例如第一页序号1,2...,第二页序号11,12...,请回复

**Comment by yanbowe** [comment]
让后端返给你不更好吗？

**Comment by stevenliu87** [comment]
应该和分页有关 2.0的不会写

**Comment by yanbowe** [comment]
序号的话，可以使用 customRender， 但是翻页递增的话你需要额外处理下，比如大于第二页加上pageSize
![image](https://user-images.githubusercontent.com/43030980/134485838-4afcc026-9d45-43ff-85c2-81351dc57e33.png)
![image](https://user-images.githubusercontent.com/43030980/134485871-f0084eb8-1968-44ad-9d5e-609334038cdc.png)

**Comment by stevenliu87** [comment]
就是分页时 不会写

**Comment by buqiyuan** [comment]
> 就是分页时 不会写

![image](https://user-images.githubusercontent.com/39730999/134487188-ca395f2b-ef24-427f-a1c4-fa59e5f6f4c1.png)
要不你在这里把分页参数传出去，或者在外部通过表格ref实例获取分页参数，暂时先这样解决吧！后面会重构

**Comment by stevenliu87** [comment]
给个实例吧 没懂
