### ISSUE TITLE
请教个问题，有个页面不在菜单里，怎么跳转

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#55]
页面不需要在菜单里显示，例如，新增表单是一个页面，用router.push()跳转，可没有这个路由，怎么实现

**Comment by stevenliu87** [comment]
很需要 请回复

**Comment by yanbowe** [comment]
> 页面不需要在菜单里显示，例如，新增表单是一个页面，用router.push()跳转，可没有这个路由，怎么实现

那你查下你有没有写这个页面的路由呀

**Comment by stevenliu87** [comment]
在哪里写呀

**Comment by yanbowe** [comment]
建议你先去学下基础,你这种问题没办法回复你

**Comment by stevenliu87** [comment]
你没理解我说的问题，这个页面不需要在菜单里显示

**Comment by yanbowe** [comment]
> 你没理解我说的问题，这个页面不需要在菜单里显示

那你在菜单的meta里面设置hidden:true

**Comment by stevenliu87** [comment]
设置hidden:true 没启作用

**Comment by stevenliu87** [comment]
例如 把 自定义模态框 菜单 隐藏，然后通过 router.push()跳转到  自定义模态框 页面

**Comment by yanbowe** [comment]
这里hidden控制显示有bug，多级路由控制无效，我这边简单修改了下，增加如下代码可实现hidden控制
![image](https://user-images.githubusercontent.com/43030980/134870198-82f56c91-8d25-4cc6-93bb-43c251e6a7fb.png)

**Comment by stevenliu87** [comment]
这个代码放到github上了吗

**Comment by yanbowe** [comment]
> 这个代码放到github上了吗

没有，这个要等作者修复才可以

**Comment by stevenliu87** [comment]
我照你的写 不行呀，菜单里是写 meta: {
          hidden: true
        }吧

**Comment by stevenliu87** [comment]
行了 我写的是父菜单 不行 我再看下

**Comment by yanbowe** [comment]
其实只写这个就行了
![image](https://user-images.githubusercontent.com/43030980/134876333-36cd1b6a-0498-4ebf-b381-5307041cb2c4.png)
