### ISSUE TITLE
大神请教下 如果我是动态表单 rules里想验证密码 确认密码这样交互 如何解决呢

### ISSUE THREAD

**Issue by xlanghejianfeng** [buqiyuan/vue3-antd-admin#6]

**Comment by buqiyuan** [comment]
刚刚更新了下demo[表单验证](http://buqiyuan.gitee.io/vue3-antd-admin/#/demos/form)，你看下。
详细的验证方式可以参考[async-validator](https://github.com/yiminghe/async-validator)

**Comment by xlanghejianfeng** [comment]
多谢🙏，学习下您的思路，差点使用vuex来临存暂解决&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bqy <notifications@github.com&gt;
发送时间: 2020年12月15日 22:26
收件人: buqiyuan/vue3-antd-admin <vue3-antd-admin@noreply.github.com&gt;
抄送: xlanghejianfeng <717560379@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[buqiyuan/vue3-antd-admin] 大神请教下 如果我是动态表单 rules里想验证密码 确认密码这样交互 如何解决呢 (#6)
