### ISSUE TITLE
启动报错，如图，还有旧版的swagger文档地址没了？？

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antd-admin#61]
![image](https://user-images.githubusercontent.com/77230009/145669915-6edfb3b1-1c19-4b18-84a3-122b39629a82.png)

**Comment by tiantianliulang** [comment]
emmm, 错误找到了。。   swagger地址能放出来嘛

**Comment by buqiyuan** [comment]
[swagger地址](http://29135jo738.zicp.vip/swagger-api/static/index.html)，建议你还是拉后端代码本地跑吧
