### ISSUE TITLE
生产环境中useCreateModal无法使当前模态框继承App实例上下文

### ISSUE THREAD

**Issue by checkhout** [buqiyuan/vue3-antd-admin#62]
通过断点发现生产环境useCreateModal.js中的_app._instance为null

而在生产环境的runtime-core.esm-bundler.js中：
if ((process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__) {
    app._instance = vnode.component;
    devtoolsInitApp(app, version); // 这里为 app实例的_instance赋值了，但是生产环境则没有这一步了
}

大佬你最新的代码是舍弃了useCreateModal这个方法了吗？

**Comment by buqiyuan** [comment]
是的，useCreateModal已经舍弃了，之前的一些旧代码还没删干净

**Comment by buqiyuan** [comment]
替换方法是[useModal](https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/hooks/useModal/index.ts)
