### ISSUE TITLE
大佬没有装eslint吗，项目好多警告

### ISSUE THREAD

**Issue by RuoFeng2015** [buqiyuan/vue3-antd-admin#7]
大佬没有装eslint吗，项目好多警告

**Comment by buqiyuan** [comment]
装了呀！是不是你依赖没下好？或是编辑器没load好

**Comment by RuoFeng2015** [comment]
![image](https://user-images.githubusercontent.com/41161634/103094698-5fd7f200-4639-11eb-9cec-404e5e67b391.png)
我把node_modules删除，重新yarn install 一遍还是一样

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/103094942-e7bdfc00-4639-11eb-89ed-f5d7f979b2c9.png)
噢噢，原来是这种警告啊！变量定义了却没使用就会出现这种警告，你可以在.eslintrc.js里面开启，不过开启后你后续写代码可能就有些痛苦哈哈~

**Comment by RuoFeng2015** [comment]
大佬，你为什么不把你没用到的东西删除了 哭.jpg

**Comment by buqiyuan** [comment]
😂啊这个，可能主要还是因为懒吧！😝

**Comment by RuoFeng2015** [comment]
想用一下你的模板，但是看到两百多个警告，感觉要放弃了 😂

- [ ]

**Comment by buqiyuan** [comment]
😂啊哈，有时间我改善一下吧！因为这个no-unused-vars的确有些烦人
