### ISSUE TITLE
问下 table还支持customRender吗

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#76]
customRender: (value) => {
      switch (value) {
        case "0":
          return "手动";
          break;
        case "1":
          return "自动";
          break; 
        default:
          return "";
      }
    },
这样写 报错

**Comment by buqiyuan** [comment]
表格组件是完全支持antdv官方table的所有API的，我刚刚复制你这段代码运行了下是没有报错的，只是typescript会提示你的switch case值类型不兼容，你可以把你的错误信息截图看下

**Comment by stevenliu87** [comment]
错误：类型“string”不可与类型“{ value: any; text: any; record: any; index: number; column: ColumnType<any>; }”进行比较，
请回复

**Comment by buqiyuan** [comment]
请截图具体错误代码吧！看是不是我ts类型定义问题，还是你的错误使用

**Comment by stevenliu87** [comment]
放到了columns.tsx
export const baseColumns: TableColumnItem[] = [
  {
    title: "分发方式",
    dataIndex: "ffzt",
    align: "left",
    //ellipsis: true,
    customRender: (value) => {
      switch (value) {
        case "0":
          return "手动";
          break;
        case "1":
          return "终端申请";
          break; 
        default:
          return "";
      }
    },
    width: 80,
  },

**Comment by buqiyuan** [comment]
customRender回调的value参数类型和你的switch case的值类型不相等，你应该使用value对象里面的某个属性值与之相比



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月27日(周四) 上午9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [buqiyuan/vue3-antd-admin] 问下 table还支持customRender吗 (Issue #76)




 
放到了columns.tsx
 export const baseColumns: TableColumnItem[] = [
 {
 title: "分发方式",
 dataIndex: "ffzt",
 align: "left",
 //ellipsis: true,
 customRender: (value) =&gt; {
 switch (value) {
 case "0":
 return "手动";
 break;
 case "1":
 return "终端申请";
 break;
 default:
 return "";
 }
 },
 width: 80,
 },
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
