### ISSUE TITLE
请教个问题  map is not a function

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#78]
请教个问题，const list = await getListApporgcode({ apporgcode: val });返回的是数组对象，但用list.map报 map is not a function
list是这样的
{list: Array(434)}
list: (434) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…},

**Comment by stevenliu87** [comment]
着急用 请回复

**Comment by buqiyuan** [comment]
你着急也没用，其实我没啥义务回答这种非项目bug的问题，盲猜正确用法是list.list.map

**Comment by stevenliu87** [comment]
不知道和项目有没有关系，帮看下 这样写有问题吗
onSearch : async (val: string) =>{
      const optionSel=[] as Array<any>  
     const list = await getListApporgcode({ apporgcode: val });
     console.log(list);
     
     list.map((item)=>(
      console.log(item)
      // optionSel.push({ label: item.apporgname, value: item.apporgcode })
     ));

**Comment by stevenliu87** [comment]
知道原因了，可还有个问题就是options: optionSel;已经有值了 但下拉框里不显示

**Comment by stevenliu87** [comment]
能回复下吗 用表单提交时，能动态获取下拉框的数据吗
