### ISSUE TITLE
请教 框架中怎么用description控件呀

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#80]
官网import descriptionItem from './descriptionItem/index.vue';这样写报错，components: {
DescriptionsItem:Descriptions.Item
}这样写content中的内容不显示
请回复

**Comment by stevenliu87** [comment]
已经解决了

**Comment by jiguang95** [comment]
这个是antdv官方组件使用层面的问题，你应该多看antdv官方文档
