### ISSUE TITLE
提个小优化：vuex和pinia一起使用

### ISSUE THREAD

**Issue by lpz1096** [buqiyuan/vue3-antd-admin#81]
是不是可以只使用pinia

**Comment by buqiyuan** [comment]
🤔不是很理解为什么要一起使用，两者都可以很好的满足全局状态管理需求，只是pinia相对于vuex则有更好的ts类型提示

**Comment by lpz1096** [comment]
我的意思是你项目两个都有用到，是不是只要用一个就可以了

**Comment by lpz1096** [comment]
我的意思就是只使用一个，关闭这个issue吧，我看到你之前版本有两个都一起用到，现在更新我看到只使用了pinia

**Comment by buqiyuan** [comment]
嗯？你应该是记错了吧！我一直都只使用其中一个库，不会同时使用两个功能类似的库。如果你确实看到之前的版本有这种情况，可能是我在刚重构的时候忘了卸载vuex了
