### ISSUE TITLE
表单这里逻辑视乎有问题

### ISSUE THREAD

**Issue by yaojin2070** [buqiyuan/vue3-antd-admin#82]
![image](https://user-images.githubusercontent.com/48686959/151683919-2cc27c12-ce0d-40cc-939b-653b066c3097.png)
通过props的初始值设置了formModel的值, 可是初始化的时候, 又将配置文件中的defaultValue赋值过去了, 这样的话不就props没有作用了?
![image](https://user-images.githubusercontent.com/48686959/151683948-38852356-fc88-4f36-a895-4e2351cf380a.png)

**Comment by buqiyuan** [comment]
这里的initialValues默认优先级最低的，如果schemas中的item有defaultValue且不为空，则会优先使用defaultValue

**Comment by yaojin2070** [comment]
> 这里的initialValues默认优先级最低的，如果schemas中的item有defaultValue且不为空，则会优先使用defaultValue

你这里所值的空是不为undefined或者null的情况, 如果为空字符串还是会识别进去, 我觉得这样并不好,  如果需要回显后台请求回来的数据, 我看好像只能通过setFieldsValue方法来改变, 可是每次都要去取一个ref, 好像有点不方便, 如果在内部使用watch initialValues的值 是有性能方面的问题?

**Comment by buqiyuan** [comment]
initialValues作为初始化值，顾名思义理应只有初始化时才有作用，不应参与后续的响应式中，这点在一些UI组件库中也有类似设计，而通过setFieldsValue内部方法更新值，则更容易追踪数据的变化，有时候响应式数据会给我们带来便捷的同时也会带来一些麻烦，就像vuex一样，你不应该通过修改state来更新值，而是通过commit去更新值，保证更新数据的方式只有一个入口。
    关于空值判断那里确实不足，可以在加一个判断避免覆盖原始值。

![image](https://user-images.githubusercontent.com/39730999/151685330-c51409cc-2f74-46c9-a3a5-c2ad28ed2531.png)

**Comment by buqiyuan** [comment]
你可以根据自己的需要来改造，我这个还缺乏大量业务实践，所以也不是最佳的实践方式。感谢你的反馈，后面我会结合更多业务场景进行优化和完善，若后续你实践过程中遇到什么问题也欢迎反馈~
