### ISSUE TITLE
表单vIf 多个条件控制

### ISSUE THREAD

**Issue by tiantianliulang** [buqiyuan/vue3-antd-admin#83]
我再vIf里面2个条件判断 是否显示，页面上 我点击 ‘是否外链’时  switch无效果呢, 
![image](https://user-images.githubusercontent.com/77230009/152105525-32c5c0f1-4c59-40eb-873d-3d66089f62e1.png)

**Comment by buqiyuan** [comment]
感谢反馈！已修复。问题来源于下面的错误赋值

![image](https://user-images.githubusercontent.com/39730999/152191142-cea7fdba-4fff-4c78-bbb8-86baeb9395d4.png)
