### ISSUE TITLE
150大小时新增弹框默认不居中，也不能下滚

### ISSUE THREAD

**Issue by csm12s** [buqiyuan/vue3-antd-admin#85]

**Comment by yanbowe** [comment]
给个复现？

**Comment by csm12s** [comment]
浏览器缩放比较大的时候，你可以参考
https://github.com/vbenjs/vue-vben-admin
https://vvbin.cn/next/#/system/account
![image](https://user-images.githubusercontent.com/64699457/157230828-00835236-1654-49e1-aaee-e1e161fb4f61.png)
![image](https://user-images.githubusercontent.com/64699457/157231101-f4f328f3-972f-4d5e-bbff-70f499984139.png)

**Comment by yanbowe** [comment]
目前缩放状态下应该没有考虑的，意义不大
