### ISSUE TITLE
打包编译后dynamic-table的问题

### ISSUE THREAD

**Issue by Jackie733** [buqiyuan/vue3-antd-admin#87]
打包静态部署后，dynamic-table的column-setting会报错setProps is not a function
`
watchEffect(() => {
    table.setProps({ columns: tableColumns.value });
});
`

**Comment by buqiyuan** [comment]
🤔啊这样...使用watchPostEffect代替watchEffect看看，或者table?.setProps

**Comment by Jackie733** [comment]
好像不行，会不会是`createTableContext(getCurrentInstance()!);`，实例里面并没有setProps、getColumnKey、refreshTable等

**Comment by buqiyuan** [comment]
🤔不应该呀，在setup中return的属性和方法默认都会暴露在组件实例身上的。你看我在线示例也是没有问题的，你的是什么环境下打包的 不会是SSR吧？

**Comment by Jackie733** [comment]
不是ssr，我是用`<script setup lang="ts">`这种写法。不知道是不是有关。
修改了useTableContext，不用`getCurrentInstance和ComponentInternalInstance`来注入使用实例，暂时解决问题了

**Comment by buqiyuan** [comment]
(⊙o⊙)…原来是你使用的是setup syntax，使用这种语法，内部的变量默认是闭包不可见的，即不对外暴露，需要使用defineExpose确要暴露出去的属性
![image](https://user-images.githubusercontent.com/39730999/155131976-c94a9ff5-fcac-4d4f-93e3-b6991fc9997c.png)
