### ISSUE TITLE
列表中带查询条件的是没有实现吗

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#88]
点击查询，没有传查询条件

**Comment by buqiyuan** [comment]
实现了呀，可以参考这个[demo](https://buqiyuan.gitee.io/vue3-antd-admin/#/demos/table/lol)或[代码](https://github.com/buqiyuan/vue3-antd-admin/blob/a8a3abdfeea71124443b9e5745c86efd984ec025/src/views/demos/tables/lol-table/index.vue#L81)，有个别页面的搜索条件只是摆设而已，并没有将实际的查询条件当做参数传递

**Comment by stevenliu87** [comment]
看到了，但有个问题，如果查询条件是'RangePicker',怎么能将开始和结束日期拆成两个字段传值呢

**Comment by buqiyuan** [comment]
你在调用接口之前，手动改一下参数就好了呀！这个应该不算大问题吧？如果觉得这样麻烦的话，后续我考虑一下 看看怎么支持多字段比较好

**Comment by stevenliu87** [comment]
到api接口时，怎么把一个字段拆成两个字段传值呢

**Comment by buqiyuan** [comment]
😢啊这...你看这样行吗？
```javascript 
  const loadData = async (params) => {
  const [field1, field2] = params.目标字段
   const  _params = {
       ...params,
       field1, 
       field2
   }
    const { data } = await getLolHeroList(params);
    tableData = data.list;
    return data;
  }
```
