### ISSUE TITLE
columns.tsx选择RangePicker后，能执行选择事件吗

### ISSUE THREAD

**Issue by stevenliu87** [buqiyuan/vue3-antd-admin#89]
就是想拆成两个字段，你说的在接口拆，怎么拆呀，我看了下，传的值是proxy类型的

**Comment by buqiyuan** [comment]
害，兄die，不要把issue当成聊天好吗？这个是比较基础的知识，不是框架模板层面的问题，同一个问题你在一个issue里面继续问就好了，不过我还是希望这些js基础的问题不要提issue，不是我不够热心，我也要上班的，这些问题你可以通过百度解决！如果是框架层面的问题，欢迎随时提问~

**Comment by stevenliu87** [comment]
你没理解我说的问题， {
    title: "分发时间",
    dataIndex: "applydate1",
    align: "left",
     formItemProps: {
        component: 'RangePicker',
        componentProps: {
          class: 'w-full',
        },
      },
    width: 100,
    // hideInSearch: true,
  },
这里能加事件吗，因为你关闭了问题，我才提新的问题的

**Comment by buqiyuan** [comment]
我是回答了你这个issue的第一个评论的问题。然后关于你说的这个加事件，可以参考这个[示例](https://github.com/buqiyuan/vue3-antd-admin/blob/a8a3abdfeea71124443b9e5745c86efd984ec025/src/views/demos/tables/search-table/columns.tsx#L74)
 , 其实具体使用方式已经在ts类型定义上写清楚了，如果你有看过它的相关类型定义以及具体组件的封装的话

**Comment by stevenliu87** [comment]
我想实现选择了RangePicker，把开始和结束日期给两个字段

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/155646755-e8165bde-5ca3-4f3b-945a-cf691176270f.png)
那你直接操作formModel就可以啦！你看如下行不？我没测试过
```js
   componentProps: ({ schemaFormRef, formModel }) => ({
       onChange() {
          formModel['field1'] = formModel['applydate1'][0];
          formModel['field2'] = formModel['applydate1'][1];
        }
      })
```
