### ISSUE TITLE
请问出现如下提示：tsconfig.json 无法写入文件...Export2Excel.js...(vscode)

### ISSUE THREAD

**Issue by kokman** [buqiyuan/vue3-antd-admin#90]
tsconfig.json 出现如下错误提示，请问如何解决？谢谢！

无法写入文件“/Users/zhaoguomin/Projects/vue/vite-vue3-admin/src/utils/Export2Excel.js”，因为它会覆盖输入文件。

**Comment by buqiyuan** [comment]
在`tsconfig.json`中，将allowJs 设置为 false即可

**Comment by kokman** [comment]
已解决，谢谢！
